### ISSUE TITLE
State of https://github.com/CommitteeOfZero/sc3ntist/pull/1

### ISSUE THREAD

**Issue by casept** [CommitteeOfZero/sc3ntist#2]
I can't get sc3ntist to build using qmake on Linux. With GCC, it tries to compile `src/parser/CCCharset.o` and eventually runs out of memory. With clang, it fails to link. Tested on both Ubuntu 22.04 and Arch. However, building using the CMakeLists.txt provided in that PR after adding `sc3ntist` as a target works just fine, despite the PR not making any changes to the offending source file.

It also adds a character set for Steins;Gate, which is quite helpful as that's the game I want to debug (See https://github.com/CommitteeOfZero/impacto/issues/12).

The C++ version bump to C++17 is also nice.

For these reasons, I'd prefer to base my debugger branch on that work. Is there any chance of the PR being accepted? If not, what would have to be fixed up to get it accepted?

**Comment by Enorovan** [comment]
A bit late but it got merged, with txt extraction on top of it
